module.exports = {
    PREFIX: [
    ],
    SUFFIX: [
        'ant.design',
        '.live.com',
        'xda-developers.com',
        'xda-cdn.com',
        'mozilla.net',
        'mozilla.org',
        'sstatic.net',
        'quantcount.com',
        'github.io',
        'vimcasts.org',
        'cloudfront.net',
        'apachefriends.org',
        'bitnami.com',
        'kotlinlang.org',
        'jetbrains.com',
        'gitbooks.io',
        'vuejs.org',
        'yesno.wtf',
        'backlog.com',
        'gitbook.com',
        'codepen.io',
        'codesandbox.io',
        'amplitude.com',
        'csb.app',
        'amazonaws.com',
        'reactjs.org',
        'bundle.run',
        'reacttraining.com',
        'babeljs.io',
        '64clouds.com',
        'docker.com',
        '.js.org',
        'perimeterx.net',
        'webassembly.org',
        'npmjs.com',
        'freecodecamp.org',
        'godaddy.com',
        'azure.com',
        'unpkg.com',
        'githubusercontent.com',
        'githubassets.com',
        'githubapp.com',
        'office365.com',
        'optimizely.com',
        'msauth.net',
    ],
    INCLUDE: [
    ],
    REGEXP: [
    ],
}
